=== g8hh/quepland2/data/Items/item-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "title": "JSON Schema for my JSON file format",

  "type": "array",

  "items": {
    "type": "object",
    "description": "An item object.",
    "properties": {
      "name": {
        "type": "string",
        "description": "The items's name. Defaults to Unset Name."
      },
      "isTome": {
        "type": "boolean",
        "description": "If the item is a tome that can be used for fast travel."
      },
      "description": {
        "type": "string",
        "description": "The item's description. Defaults to Unset Description."
      },
      "requirements": {
        "type": "array",
        "description": "The requirements to use this item.",
        "items": {
          "type": "object",
          "properties": {
            "skill": {
              "type": "string",
              "description": "The required skill. Goes with SkillLevel or defaults to 0."
            },
            "skillLevel": {
              "type": "integer",
              "description": "The skill level required. Goes with skill."
            },
            "item": {
              "type": "string",
              "description": "The name of the item required. Needs an itemAmount or defaults to 0."
            },
            "itemAmount": {
              "type": "integer",
              "description": "The amount of item required. Defaults to 0."
            },
            "action": {
              "type": "string",
              "description": "The action required. Actions are enabled from items' ActionEnabled attribute."
            },
            "location": {
              "type": "string",
              "description": "The location requirement. Uses GameState.Location as a check."
            },
            "quest": {
              "type": "string",
              "description": "The name of the quest required. Goes with minimumQuestProgress and maximumQuestProgress, which default to 0 and int.MaxValue respectively."
            },
            "areaUnlocked": {
              "type": "string",
              "description": "The area that must be unlocked. If RequireAreaLocked is set to true, then it defines the area that must be locked instead."
            },
            "lockedFollower": {
              "type": "string",
              "description": "The name of the follower that must be locked."
            },
            "requireAreaLocked": {
              "type": "boolean",
              "description": "If set to true, this changes areaUnlocked to check for the opposite, if the area is locked."
            },
            "minimumQuestProgress": {
              "type": "integer",
              "description": "The minimum progress that the quest must be. Defaults to 0."
            },
            "maximumQuestProgress": {
              "type": "integer",
              "description": "The maximum progress that the quest must be. Defaults to int.maxValue."
            }
          }
        }
      },
      "value": {
        "type": "integer",
        "description": "The item's value. Defaults to 0. Usually refers to coins, but it can be any currency in a shop."
      },
      "gatherSpeed": {
        "type": "integer",
        "description": "The speed in game ticks for the item to be gathered. Defaults to 10."
      },
      "id": {
        "type": "integer",
        "description": "This value is set automatically when items are loaded. Do not set manually in json."
      },
      "gatherSpeedBonus": {
        "type": "number",
        "description": "The percent decrease in game ticks that this item provides for the skills it enables."
      },
      "experienceGainBonus": {
        "type": "number",
        "description": "The percent bonus to experience gain in the skill set in experienceBonusSkill."
      },
      "experienceBonusSkill": {
        "type": "string",
        "description": "The skill this item applies experienceGainBonus to."
      },
      "experienceGained": {
        "type": "string",
        "description": "The experience gained by gathering this skill. Format is Skill:Amount"
      },
      "openCraftingMenuText": {
        "type": "string",
        "description": "Special text for a button that will take the player to the crafting menu."
      },
      "category": {
        "type": "string",
        "description": "This is set on game load and should not be set manually."
      },
      "enabledActions": {
        "type": "string",
        "description": "All the actions this item enables. Format doesn't matter, all checks use the string.Contains function."
      },
      "gatherString": {
        "type": "string",
        "description": "The string put in a message to the player when the item is gathered."
      },
      "icon": {
        "type": "string",
        "description": "The item's image in game. Defaults to Unset."
      },
      "equipSlot": {
        "type": "string",
        "description": "The slot this item can be equipped to. Defaults to None."
      },
      "primaryColor": {
        "type": "string",
        "description": "This is set per object group on load. Do not set manually."
      },
      "secondaryColor": {
        "type": "string",
        "description": "The color for the top left of the item icon. Defaults to lightgray. Can be any html color or hex value with #."
      },
      "parameter": {
        "type": "string",
        "description": "The parameter used for objects with the same name. Used in the uniqueID to make items unique."
      },
      "isStackable": {
        "type": "boolean",
        "description": "Sets the item to stackable. Defaults to false."
      },
      "isEquipped": {
        "type": "boolean",
        "description": "Don't set in json."
      },
      "isSellable": {
        "type": "boolean",
        "description": "Makes items sellable. Defaults to true, unless it's a questItem."
      },
      "rerender": {
        "type": "boolean",
        "description": "Used in rendering. Don't set in json."
      },
      "armorInfo": {
        "type": "object",
        "description": "The armor data of the item.",
        "properties": {
          "damage": {
            "type": "integer",
            "description": "The added damage of the item when worn."
          },
          "armorBonus": {
            "type": "integer",
            "description": "The added armor bonus of the item when worn."
          },
          "wearRequirements": {
            "type": "array",
            "description": "The requirements to wear this item.",
            "items": {
              "type": "object",
              "properties": {
                "skill": {
                  "type": "string",
                  "description": "The required skill. Goes with SkillLevel or defaults to 0."
                },
                "skillLevel": {
                  "type": "integer",
                  "description": "The skill level required. Goes with skill."
                },
                "item": {
                  "type": "string",
                  "description": "The name of the item required. Needs an itemAmount or defaults to 0."
                },
                "itemAmount": {
                  "type": "integer",
                  "description": "The amount of item required. Defaults to 0."
                },
                "action": {
                  "type": "string",
                  "description": "The action required. Actions are enabled from items' ActionEnabled attribute."
                },
                "location": {
                  "type": "string",
                  "description": "The location requirement. Uses GameState.Location as a check."
                },
                "quest": {
                  "type": "string",
                  "description": "The name of the quest required. Goes with minimumQuestProgress and maximumQuestProgress, which default to 0 and int.MaxValue respectively."
                },
                "areaUnlocked": {
                  "type": "string",
                  "description": "The area that must be unlocked. If RequireAreaLocked is set to true, then it defines the area that must be locked instead."
                },
                "lockedFollower": {
                  "type": "string",
                  "description": "The name of the follower that must be locked."
                },
                "requireAreaLocked": {
                  "type": "boolean",
                  "description": "If set to true, this changes areaUnlocked to check for the opposite, if the area is locked."
                },
                "minimumQuestProgress": {
                  "type": "integer",
                  "description": "The minimum progress that the quest must be. Defaults to 0."
                },
                "maximumQuestProgress": {
                  "type": "integer",
                  "description": "The maximum progress that the quest must be. Defaults to int.maxValue."
                }
              }
            }
          },
          "statusEffectData": {
            "type": "object",
            "description": "The status effect this armor can cause.",
            "properties": {
              "name": {
                "type": "string",
                "description": "The name of the effect. Must be set up in the BattleManager to function properly."
              },
              "speed": {
                "type": "integer",
                "description": "The number of game ticks between procs of the effect. For example, poison may have a speed of 5 and hurt the opponent once every 5 game ticks."
              },
              "duration": {
                "type": "integer",
                "description": "The number of procs before the effect wears off. An effect with a duration of 10 and speed of 2 will last 20 total game ticks."
              },
              "message": {
                "type": "string",
                "description": "The message the player sees when the effect procs."
              },
              "procOdds": {
                "type": "number",
                "minimum": 0.001,
                "maximum": 0.999,
                "description": "The odds on being hit that the effect with occur. Range of 0.001 to 0.999."
              },
              "power": {
                "type": "integer",
                "description": "The strength of the effect. Some effects don't use Power, others do. Depends on the effect."
              },
              "selfInflicted": {
                "type": "boolean",
                "description": "Determines whether the effect happens to the user or the opponent. Defaults to false (Opponent)."
              }
            }
          }
        }
      },
      "weaponInfo": {
        "type": "object",
        "description": "The weapon data of the item.",
        "properties": {
          "attackSpeed": {
            "type": "integer",
            "description": "The speed in gameticks of the weapon."
          },
          "isArrow": {
            "type": "boolean",
            "description": "Whether or not the item is an arrow."
          },
          "damage": {
            "type": "integer",
            "description": "The added damage of the item when worn."
          },
          "armorBonus": {
            "type": "integer",
            "description": "The added armor bonus of the item when worn."
          },
          "wearRequirements": {
            "type": "array",
            "description": "The requirements to wear this item.",
            "items": {
              "type": "object",
              "properties": {
                "skill": {
                  "type": "string",
                  "description": "The required skill. Goes with SkillLevel or defaults to 0."
                },
                "skillLevel": {
                  "type": "integer",
                  "description": "The skill level required. Goes with skill."
                },
                "item": {
                  "type": "string",
                  "description": "The name of the item required. Needs an itemAmount or defaults to 0."
                },
                "itemAmount": {
                  "type": "integer",
                  "description": "The amount of item required. Defaults to 0."
                },
                "action": {
                  "type": "string",
                  "description": "The action required. Actions are enabled from items' ActionEnabled attribute."
                },
                "location": {
                  "type": "string",
                  "description": "The location requirement. Uses GameState.Location as a check."
                },
                "quest": {
                  "type": "string",
                  "description": "The name of the quest required. Goes with minimumQuestProgress and maximumQuestProgress, which default to 0 and int.MaxValue respectively."
                },
                "areaUnlocked": {
                  "type": "string",
                  "description": "The area that must be unlocked. If RequireAreaLocked is set to true, then it defines the area that must be locked instead."
                },
                "lockedFollower": {
                  "type": "string",
                  "description": "The name of the follower that must be locked."
                },
                "requireAreaLocked": {
                  "type": "boolean",
                  "description": "If set to true, this changes areaUnlocked to check for the opposite, if the area is locked."
                },
                "minimumQuestProgress": {
                  "type": "integer",
                  "description": "The minimum progress that the quest must be. Defaults to 0."
                },
                "maximumQuestProgress": {
                  "type": "integer",
                  "description": "The maximum progress that the quest must be. Defaults to int.maxValue."
                }
              }
            }
          },
          "statusEffectData": {
            "type": "array",
            "description": "The status effect this armor can cause.",
            "items": {
              "properties": {
                "name": {
                  "type": "string",
                  "description": "The name of the effect. Must be set up in the BattleManager to function properly."
                },
                "speed": {
                  "type": "integer",
                  "description": "The number of game ticks between procs of the effect. For example, poison may have a speed of 5 and hurt the opponent once every 5 game ticks."
                },
                "duration": {
                  "type": "integer",
                  "description": "The number of procs before the effect wears off. An effect with a duration of 10 and speed of 2 will last 20 total game ticks."
                },
                "message": {
                  "type": "string",
                  "description": "The message the player sees when the effect procs."
                },
                "procOdds": {
                  "type": "number",
                  "minimum": 0.001,
                  "maximum": 0.999,
                  "description": "The odds on being hit that the effect with occur. Range of 0.001 to 0.999."
                },
                "power": {
                  "type": "integer",
                  "description": "The strength of the effect. Some effects don't use Power, others do. Depends on the effect."
                },
                "selfInflicted": {
                  "type": "boolean",
                  "description": "Determines whether the effect happens to the user or the opponent. Defaults to false (Opponent)."
                }
              }
            }
          },
          "alchemyInfo": {
            "type": "object",
            "description": "The alchemy data of the item.",
            "properties": {
              "queplarValue": {
                "type": "number",
                "description": "The queplar value of the item."
              },
              "queplarMultiplier": {
                "type": "number",
                "description": "The queplar multiplier of the item. Currently unused."
              }
            }
          },
          "foodInfo": {
            "type": "object",
            "description": "The food data of the item.",
            "properties": {
              "healAmount": {
                "type": "integer",
                "description": "The amount the item heals per heal tick."
              },
              "healDuration": {
                "type": "integer",
                "description": "The number of heals per item eaten."
              },
              "healSpeed": {
                "type": "integer",
                "description": "The number of game ticks between heals. Default is 5."
              },
              "buffAmount": {
                "type": "integer",
                "description": "The amount the item buffs the BuffedSkill."
              },
              "buffedSkill": {
                "type": "string",
                "description": "The skill the item buffs."
              }
            }
          },
          "TrapInfo": {
            "type": "object",
            "description": "The trap data of the item.",
            "properties": {
              "timeToReady": {
                "type": "integer",
                "description": "The number minutes it takes for the trap to be ready to harvest. Default is 90."
              },
              "size": {
                "type": "integer",
                "description": "The amount of animals caught per trapping."
              }
            }
          },
          "tanningInfo": {
            "type": "object",
            "description": "The tanning data of the item.",
            "properties": {
              "tansIntoString": {
                "type": "string",
                "description": "The name of the item this item tans into."
              }
            }
          }
        }
      }
    }
  }
}

=== g8hh/quepland2/data/Items/Logs.json
[

  {
    "name": "White Pine Logs",
    "description": "It's a very soft wood.",
    "gatherString": "You chop some white pine logs.",
    "value": 3,
    "gatherSpeed": 15,
    "experienceGained": "Woodcutting:8",
    "icon": "Log",
    "secondaryColor": "#FFE5C4",
    "requirements": [
      {
        "skill": "Woodcutting",
        "skillLevel": 1
      },
      {
        "action": "Woodcutting"
      }
    ]
  },
  {
    "name": "Poplar Logs",
    "description": "It's a less soft wood.",
    "gatherString": "You chop some poplar logs.",
    "value": 9,
    "gatherSpeed": 25,
    "secondaryColor": "#FFDA8A",
    "experienceGained": "Woodcutting:20",
    "icon": "Log",
    "requirements": [
      {
        "skill": "Woodcutting",
        "skillLevel": 7
      },
      {
        "action": "Woodcutting"
      }
    ]
  },
  {
    "name": "Balsa Logs",
    "description": "The softest wood in the world.",
    "gatherString": "You chop some balsa logs.",
    "secondaryColor": "#fffbce",
    "value": 1,
    "gatherSpeed": 7,
    "experienceGained": "Woodcutting:18",
    "icon": "Log",
    "requirements": [
      {
        "skill": "Woodcutting",
        "skillLevel": 5
      },
      {
        "action": "Woodcutting"
      }
    ]
  },
  {
    "name": "Oak Logs",
    "description": "One of the most common types of wood.",
    "gatherString": "You chop some oak logs.",
    "value": 15,
    "gatherSpeed": 25,
    "secondaryColor": "#FFD5B0",
    "experienceGained": "Woodcutting:35",
    "icon": "Log",
    "requirements": [
      {
        "skill": "Woodcutting",
        "skillLevel": 15
      },
      {
        "action": "Woodcutting"
      }
    ]
  },
  {
    "name": "Sugar Maple Logs",
    "description": "The sugar is in the sap, not the wood.",
    "gatherString": "You chop some maple logs.",
    "gatherSpeed": 30,
    "value": 25,
    "secondaryColor": "#FFBD96",
    "experienceGained": "Woodcutting:60",
    "icon": "Log",
    "requirements": [
      {
        "skill": "Woodcutting",
        "skillLevel": 25
      },
      {
        "action": "Woodcutting"
      }
    ]
  },
  {
    "name": "Birch Logs",
    "description": "A light colored wood with white bark.",
    "gatherString": "You chop some birch logs.",
    "secondaryColor": "#FFF6E0",
    "gatherSpeed": 30,
    "value": 45,
    "experienceGained": "Woodcutting:35",
    "icon": "Log",
    "requirements": [
      {
        "skill": "Woodcutting",
        "skillLevel": 25
      },
      {
        "action": "Woodcutting"
      }
    ]
  },
  {
    "name": "Mesquite Logs",
    "description": "A set of sturdy mesquite logs.",
    "gatherString": "You chop some mesquite logs.",
    "gatherSpeed": 38,
    "value": 40,
    "secondaryColor": "#BD8F57",
    "experienceGained": "Woodcutting:100",
    "icon": "Log",
    "requirements": [
      {
        "skill": "Woodcutting",
        "skillLevel": 40
      },
      {
        "action": "Woodcutting"
      }
    ]
  },
  {
    "name": "Mahogany Logs",
    "description": "A beautiful wood often used for furniture. These will probably just end up as arrows.",
    "gatherString": "You chop some mahogany logs.",
    "gatherSpeed": 45,
    "value": 190,
    "experienceGained": "Woodcutting:80",
    "icon": "Log",
    "secondaryColor": "#AB5F29",
    "requirements": [
      {
        "skill": "Woodcutting",
        "skillLevel": 52
      },
      {
        "action": "Woodcutting"
      }
    ]
  },
  {
    "name": "Ironwood Logs",
    "description": "Is it iron? Is it wood?",
    "gatherString": "You chop some ironwood logs.",
    "gatherSpeed": 55,
    "value": 90,
    "secondaryColor": "#9C491F",
    "experienceGained": "Woodcutting:165",
    "icon": "Log",
    "requirements": [
      {
        "skill": "Woodcutting",
        "skillLevel": 65
      },
      {
        "action": "Woodcutting"
      }
    ]
  },
  {
    "name": "Stormwood Logs",
    "description": "There is something strange about these logs...",
    "gatherString": "You chop some stormwood logs.",
    "gatherSpeed": 35,
    "value": 10,
    "secondaryColor": "#72b584",
    "experienceGained": "Woodcutting:165",
    "icon": "Log",
    "requirements": [
      {
        "skill": "Woodcutting",
        "skillLevel": 75
      },
      {
        "action": "Woodcutting"
      }
    ]
  },
  {
    "name": "Snakewood Logs",
    "description": "A dense, twisty wood named after the tree's snakelike appearance.",
    "gatherString": "You chop some snakewood logs.",
    "gatherSpeed": 75,
    "value": 130,
    "secondaryColor": "#824121",
    "experienceGained": "Woodcutting:240",
    "icon": "Log",
    "requirements": [
      {
        "skill": "Woodcutting",
        "skillLevel": 72
      },
      {
        "action": "Woodcutting"
      }
    ]
  },
  {
    "name": "Lignum Vitae Logs",
    "description": "The latin name accounts for half the weight of these dense logs.",
    "gatherString": "You chop some lignum vitae logs.",
    "gatherSpeed": 85,
    "value": 300,
    "secondaryColor": "#612901",
    "experienceGained": "Woodcutting:350",
    "icon": "Log",
    "requirements": [
      {
        "skill": "Woodcutting",
        "skillLevel": 85
      },
      {
        "action": "Woodcutting"
      }
    ]
  },
  {
    "name": "Buloke Logs",
    "description": "The hardest normal wood known to man. A single pound can weigh as much as 15 pounds!",
    "gatherString": "You chop some buloke logs.",
    "gatherSpeed": 105,
    "value": 500,
    "secondaryColor": "#875B24",
    "experienceGained": "Woodcutting:600",
    "icon": "Log",
    "requirements": [
      {
        "skill": "Woodcutting",
        "skillLevel": 92
      },
      {
        "action": "Woodcutting"
      }
    ]
  },
  {
    "name": "Ice Logs",
    "description": "Frozen logs from a tree made of ice.",
    "gatherString": "You chop some ice logs.",
    "gatherSpeed": 120,
    "value": 850,
    "secondaryColor": "#D2FFF5",
    "experienceGained": "Woodcutting:820",
    "icon": "Log",
    "requirements": [
      {
        "skill": "Woodcutting",
        "skillLevel": 98
      },
      {
        "action": "Woodcutting"
      }
    ]
  },
  {
    "name": "Great Tree Logs",
    "description": "Magical logs harvested from the Great Tree. They're tougher than any normal log you'll find.",
    "gatherString": "You chop some logs off the Great Tree.",
    "gatherSpeed": 135,
    "value": 1500,
    "experienceGained": "Woodcutting:600",
    "icon": "Log",
    "secondaryColor": "#9F6F4F",
    "requirements": [
      {
        "skill": "Woodcutting",
        "skillLevel": 105
      },
      {
        "action": "Woodcutting"
      }
    ]
  },
  {
    "name": "Woodcutter's Hat",
    "description": "A special hat for woodcutters.",
    "gatherString": "You found a hat!",
    "value": 2000,
    "secondaryColor": "#9F6F4F",
    "gatherSpeed": 220,
    "experienceGained": "Woodcutting:2000",
    "icon": "WoodcutterHat",
    "experienceGainBonus": 0.025,
    "experienceBonusSkill": "Woodcutting",
    "equipSlot": "Head",
    "armorInfo": {
      "armorBonus": 3
    }
  },
  {
    "name": "Tome of Logs",
    "description": "A book containing knowledge of woodcutting.",
    "value": 50,
    "icon": "Book",
    "isTome": true
  }
]
